### ISSUE TITLE
zrpy.f5.si

### ISSUE THREAD

**Issue by tw1tt3r** [zrpy/zrpy.github.io#1]
アクセスできません

**Comment by zrpy** [comment]
ドメインのnsレコードを違うやつに変えたから使えません

**Comment by tw1tt3r** [comment]
> ドメインのnsレコードを違うやつに変えたから使えません

変えないで

**Comment by zrpy** [comment]
> > ドメインのnsレコードを違うやつに変えたから使えません
> 
> 変えないで

嫌です

**Comment by tw1tt3r** [comment]
ありがとうございます
